---
- name: Ensure the git user
  user:
    name: git
    shell: /usr/bin/git-shell
    home: "{{ bare_repo_dir }}"

- name: Set authorized_keys
  authorized_key:
    user: git
    state: present
    key: "https://github.com/{{ bare_repo_user }}.keys"

- name: Initialize the bare repo
  git:
    bare: true
    dest: "{{ bare_repo_dir }}/{{ bare_repo_name }}"
    repo: "{{ bare_repo_url }}"
