---
- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: latest

- name: Bind dnsmasq to localhost
  lineinfile:
    dest: /etc/dnsmasq.conf
    state: present
    line: 'listen-address=127.0.0.1'

- name: use root user for dnsmasq
  lineinfile:
    dest: /etc/dnsmasq.conf
    state: present
    line: 'user=root'

- name: Add base dns settings
  copy:
    src: base.conf
    dest: /etc/dnsmasq.d/base.conf

- name: (re)start dnsmasq
  service:
    name: dnsmasq
    state: restarted
