---
  - name: Install dnsmasq
    apt:
      name: dnsmasq
      state: latest

  - name: Bind dnsmasq to localhost
    lineinfile:
      dest: /etc/dnsmasq.conf
      state: present
      line: 'listen-address=127.0.0.1'

  - name: user=root dnsmasq
    lineinfile:
      dest: /etc/dnsmasq.conf
      state: present
      line: 'user=root'

  - name: Add localhost to resolv.conf
    lineinfile:
      dest: /etc/resolv.conf
      state: present
      line: 'nameserver 127.0.0.1'
      insertbefore: BOF

  - name: Add port to resolv.conf
    lineinfile:
      dest: /etc/resolv.conf
      state: present
      line: 'port 8600'
      insertbefore: BOF

  - name: Launch dnsmasq
    service:
      name: dnsmasq
      state: started
