---
- name: check for docker bin
  stat:
    path: /usr/bin/docker
  register: docker

- name: check for docker install script
  stat:
    path: /tmp/get-docker.sh
  register: dockerInstallScript

- name: Get docker install script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
  when: (docker.stat.exists == False) and
        (dockerInstallScript.stat.exists == False)

- name: Install docker
  become: true
  shell: "sh /tmp/get-docker.sh"
  when: (docker.stat.exists == False)

# - name: install helpers
#   apt:
#     name: "{{ item }}"
#     state: present
#   with_items:
#     - apt-transport-https
#     - ca-certificates
#     - curl
#     - gnupg2
#     - software-properties-common
#   when: (docker.stat.exists == False)
#
# - name: Add docker to apt
#   apt_repository:
#     repo: deb [arch=armhf] https://download.docker.com/linux/debian stretch stable
#     state: present
#   when: (docker.stat.exists == False)
#
# - name: Install docker
#   apt:
#     update_cache: true
#     name: docker-ce
#     state: removed
#   when: (docker.stat.exists == False)
