---
  - name: Add consul to dnsmasq
    lineinfile: dest=/etc/dnsmasq.conf state=present line='server=/consul/127.0.0.1#8600'

  - name: Restart dnsmasq
    service:
      name: dnsmasq
      state: restarted
